version: '3.4'

services:
  amazingapi-api:
    image: amazingapi/api:1.0.0
    build:
      context: ../
      args:
        feed: ${FEED}
        configuration: ${CONFIGURATION}
      dockerfile: src/OneInc.AmazingApi.Api/Dockerfile